"""Build post-composited document and hospital plates for the tone proof.

Plot-critical text is never generated by an image model. These plates are the
source stills for P05–P08 and are animated only as paper slides / stamp hits.
"""

from __future__ import annotations

import pathlib

from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageFont

PROJECT = pathlib.Path(__file__).resolve().parents[1]
REFS = PROJECT / "out" / "approved_references"
STATES = PROJECT / "out" / "approved_states"
DEST = PROJECT / "out" / "proof_documents"
FRAMES = PROJECT / "out" / "proof_keyframes"

FONT_REG = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONT_BOLD = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
FONT_MONO = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"


def font(path: str, size: int) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype(path, size)
    except OSError:
        return ImageFont.truetype(FONT_REG, size)


def paper_base(size: tuple[int, int] = (1600, 1000)) -> Image.Image:
    img = Image.new("RGB", size, (232, 224, 204))
    draw = ImageDraw.Draw(img)
    # faint ruled texture
    for y in range(70, size[1] - 40, 28):
        draw.line([(48, y), (size[0] - 48, y)], fill=(214, 206, 186), width=1)
    noise = Image.effect_noise(size, 12).convert("L")
    paper = ImageEnhance.Contrast(noise).enhance(0.35)
    img = Image.blend(img, Image.merge("RGB", (paper, paper, paper)), 0.08)
    return img


def draw_receipt(date_line: str, filename: str) -> pathlib.Path:
    img = paper_base((1400, 900))
    d = ImageDraw.Draw(img)
    title = font(FONT_BOLD, 42)
    body = font(FONT_MONO, 34)
    small = font(FONT_REG, 26)
    d.text((70, 48), "ST. ORISON MUNICIPAL CAFETERIA", fill=(40, 42, 40), font=title)
    d.text((70, 104), "PURCHASE RECEIPT — RETAIN FOR AUDIT", fill=(90, 70, 55), font=small)
    lines = [
        ("PURCHASER", "JUNE HAVEL"),
        ("LOCATION", "CAFETERIA"),
        ("ITEM", "COFFEE / STONEWARE SERVICE"),
        ("TIME", "08:43"),
        ("PURCHASE DATE", date_line),
        ("REGISTER", "03"),
        ("OPERATOR", "K. ELLIS"),
    ]
    y = 180
    for label, value in lines:
        d.text((70, y), f"{label:14}", fill=(70, 72, 70), font=body)
        d.text((420, y), value, fill=(28, 28, 28), font=body)
        y += 70
    d.rectangle([(70, y + 10), (1330, y + 12)], fill=(120, 36, 40))
    d.text((70, y + 30), "EVIDENCE CROSS-REF  OBSERVED MONDAY 11", fill=(90, 40, 40), font=small)
    DEST.mkdir(parents=True, exist_ok=True)
    path = DEST / filename
    img.save(path, quality=95)
    return path


def draw_evidence_tag() -> pathlib.Path:
    img = Image.new("RGB", (900, 360), (245, 238, 214))
    d = ImageDraw.Draw(img)
    d.rectangle([(8, 8), (891, 351)], outline=(40, 40, 40), width=4)
    d.text((36, 28), "PROPERTY — CONTINUITY HOLD", fill=(90, 30, 30), font=font(FONT_BOLD, 36))
    body = font(FONT_MONO, 28)
    for i, line in enumerate(
        [
            "OBJECT: CREAM STONEWARE MUG / COBALT STRIPE",
            "OBSERVED: MONDAY 11  08:43",
            "HOLDER: JUNE HAVEL",
            "STATUS: PREMATURE / UNDER DOME",
        ]
    ):
        d.text((36, 100 + i * 52), line, fill=(30, 30, 30), font=body)
    path = DEST / "evidence_tag.jpg"
    img.save(path, quality=95)
    return path


def stamp_overlay(text: str = "AUTHORITATIVE") -> pathlib.Path:
    img = Image.new("RGBA", (720, 220), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rectangle([(16, 16), (703, 203)], outline=(124, 36, 43, 230), width=8)
    d.rectangle([(28, 28), (691, 191)], outline=(124, 36, 43, 180), width=3)
    d.text((70, 70), text, fill=(124, 36, 43, 230), font=font(FONT_BOLD, 64))
    path = DEST / "stamp_authoritative.png"
    img.save(path)
    return path


def overhead_pair(receipt: pathlib.Path, tag: pathlib.Path, out_name: str) -> pathlib.Path:
    """Compose P05-style overhead insert on a desk plate."""
    canvas = Image.new("RGB", (1920, 1080), (90, 92, 88))
    # desk surface
    desk = Image.new("RGB", (1920, 1080), (156, 152, 142))
    desk = ImageEnhance.Brightness(desk).enhance(0.95)
    canvas.paste(desk, (0, 0))
    r = Image.open(receipt).convert("RGB").resize((980, 630), Image.Resampling.LANCZOS)
    r = r.rotate(-4, expand=True, fillcolor=(156, 152, 142))
    t = Image.open(tag).convert("RGB").resize((620, 250), Image.Resampling.LANCZOS)
    t = t.rotate(3, expand=True, fillcolor=(156, 152, 142))
    canvas.paste(r, (80, 180))
    canvas.paste(t, (1180, 620))
    # soft vignette / film
    canvas = ImageEnhance.Color(canvas).enhance(0.85)
    path = DEST / out_name
    canvas.save(path, quality=94)
    return path


def hospital_card(name: str, date: str) -> Image.Image:
    card = Image.new("RGB", (520, 180), (236, 232, 220))
    d = ImageDraw.Draw(card)
    d.rectangle([(4, 4), (515, 175)], outline=(60, 60, 60), width=3)
    d.text((24, 22), "ST. ORISON ADMISSION", fill=(90, 40, 40), font=font(FONT_BOLD, 28))
    d.text((24, 70), f"PATIENT: {name}", fill=(20, 20, 20), font=font(FONT_MONO, 26))
    d.text((24, 118), f"ADMITTED: {date}", fill=(20, 20, 20), font=font(FONT_MONO, 26))
    return card


def hospital_plate(patient: pathlib.Path, name: str, out_name: str, mug: pathlib.Path | None = None) -> pathlib.Path:
    base = Image.open(patient).convert("RGB").resize((1920, 1080), Image.Resampling.LANCZOS)
    card = hospital_card(name, "FRIDAY 8")
    # place card on lower-left bedside area
    base.paste(card, (60, 820))
    if mug and mug.exists():
        # Mug identity boards are multi-view sheets — crop one cell, not the grid.
        sheet = Image.open(mug).convert("RGB")
        w, h = sheet.size
        cell = sheet.crop((0, 0, w // 3, h // 2)).resize((110, 110), Image.Resampling.LANCZOS)
        base.paste(cell, (1760, 920))
    path = DEST / out_name
    base.save(path, quality=94)
    return path


def receipt_slide_over_hospital(
    hospital: pathlib.Path, receipt: pathlib.Path, out_name: str, occlusion: float
) -> pathlib.Path:
    """occlusion 0..1 — how far the receipt has slid across the patient region."""
    base = Image.open(hospital).convert("RGB")
    r = Image.open(receipt).convert("RGB").resize((1100, 700), Image.Resampling.LANCZOS)
    # patient region roughly left half; slide from left
    x = int(-1100 + occlusion * (1100 + 200))
    y = 220
    layer = base.copy()
    layer.paste(r, (x, y))
    path = DEST / out_name
    layer.save(path, quality=94)
    return path


def main() -> None:
    DEST.mkdir(parents=True, exist_ok=True)
    thu = draw_receipt("THURSDAY 14", "receipt_thursday.jpg")
    fri = draw_receipt("FRIDAY 8", "receipt_friday.jpg")
    tag = draw_evidence_tag()
    stamp_overlay()
    overhead_pair(thu, tag, "P05_overhead_thursday.jpg")
    overhead_pair(fri, tag, "P06_overhead_friday.jpg")
    june = hospital_plate(STATES / "hospital_june.jpg", "JUNE HAVEL", "P07_hospital_june.jpg", REFS / "mug.jpg")
    peter = hospital_plate(STATES / "hospital_peter.jpg", "PETER GRAY", "P08_hospital_peter.jpg", REFS / "mug.jpg")
    # intermediate occlusion frames for wipe-under-paper
    for i, occ in enumerate([0.15, 0.45, 0.75, 1.0]):
        receipt_slide_over_hospital(june, fri, f"P07_slide_{i:02d}.jpg", occ)
    for i, occ in enumerate([1.0, 0.75, 0.45, 0.15, 0.0]):
        src = peter if occ < 0.55 else june
        # when fully covered, swap to peter underneath
        if occ >= 0.75:
            src = june
        elif occ <= 0.45:
            src = peter
        else:
            src = peter
        receipt_slide_over_hospital(src, fri, f"P08_reveal_{i:02d}.jpg", occ)
    # clean copies into proof_keyframes for review
    FRAMES.mkdir(parents=True, exist_ok=True)
    for name in ("P05_overhead_thursday.jpg", "P06_overhead_friday.jpg", "P07_hospital_june.jpg", "P08_hospital_peter.jpg"):
        Image.open(DEST / name).save(FRAMES / name, quality=94)
    print(DEST)


if __name__ == "__main__":
    main()
